Importações

In [1]:
import pandas as pd

In [2]:
vendas = pd.read_excel('Vendas.xlsx')
display(vendas)

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,1,2019-01-01,Iguatemi Esplanada,Sapato Estampa,1,358,358
1,1,2019-01-01,Iguatemi Esplanada,Camiseta,2,180,360
2,1,2019-01-01,Iguatemi Esplanada,Sapato Xadrez,1,368,368
3,2,2019-01-02,Norte Shopping,Relógio,3,200,600
4,2,2019-01-02,Norte Shopping,Chinelo Liso,1,71,71
...,...,...,...,...,...,...,...
93905,65012,2019-11-30,Shopping Vila Velha,Mochila Xadrez,2,283,566
93906,65013,2019-11-30,Ribeirão Shopping,Pulseira Listrado,2,79,158
93907,65013,2019-11-30,Ribeirão Shopping,Cueca Listrado,3,67,201
93908,65014,2019-11-30,Shopping Morumbi,Pulseira Linho,5,114,570
93909,65014,2019-11-30,Shopping Morumbi,Casaco Xadrez,4,259,1036

In [9]:
iguatemi = vendas.loc[vendas['ID Loja'] == 'Iguatemi Esplanada']
morumbi = vendas.loc[vendas['ID Loja'] == 'Shopping Morumbi']
norte = vendas.loc[vendas['ID Loja'] == 'Norte Shopping']
ribeirao = vendas.loc[vendas['ID Loja'] == 'Ribeirão Shopping']
fortaleza = vendas.loc[vendas['ID Loja'] == 'Rio Mar Shopping Fortaleza']
bourbon = vendas.loc[vendas['ID Loja'] == 'Bourbon Shopping SP']
uberlandia = vendas.loc[vendas['ID Loja'] == 'Center Shopping Uberlândia']
campinas = vendas.loc[vendas['ID Loja'] == 'Iguatemi Campinas']

In [10]:
iguatemi.drop(["ID Loja"], axis=1, inplace=True)
display(iguatemi)

C:\Users\Robso\AppData\Local\Temp\ipykernel_7220\3158247264.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iguatemi.drop(["ID Loja"], axis=1, inplace=True)

,Código Venda,Data,Produto,Quantidade,Valor Unitário,Valor Final
0,1,2019-01-01,Sapato Estampa,1,358,358
1,1,2019-01-01,Camiseta,2,180,360
2,1,2019-01-01,Sapato Xadrez,1,368,368
26,21,2019-01-02,Camisa Gola V Listrado,2,116,232
44,34,2019-01-02,Sapato Listrado,1,363,363
...,...,...,...,...,...,...
93745,64908,2019-11-30,Meia,4,30,120
93776,64928,2019-11-30,Tênis Xadrez,3,259,777
93880,64993,2019-11-30,Bermuda Liso,2,157,314
93881,64993,2019-11-30,Chinelo Xadrez,1,66,66
93882,64993,2019-11-30,Cinto Liso,1,209,209

In [ ]:
with pd.ExcelWriter("Iguatemi Esplanada.xlsx", mode="w", engine="openpyxl") as writer:
    iguatemi.to_excel(writer) 
with pd.ExcelWriter("Shopping Morumbi.xlsx", mode="w", engine="openpyxl") as writer:
    morumbi.to_excel(writer)